### ISSUE TITLE
can't get the pretrained model

### ISSUE THREAD

**Issue by kidwhh** [fvmassoli/cross-resolution-face-recognition#10]
sorry , i can't get the pretrained model from https://drive.google.com/file/d/17AVPBQFtrIJwo3yPm4sNls7ZSyswFsvT/view?usp=sharing, the file is not exist.

**Comment by fvmassoli** [comment]
Here is the new link

https://github.com/ox-vgg/vgg_face2.

The model is the SE-ResNet-50 with features dim = 2048.
