### ISSUE TITLE
Can not download the pretrain SE-ResNet-50 model?

### ISSUE THREAD

**Issue by Watebear** [fvmassoli/cross-resolution-face-recognition#12]
Hello, I am very interest in your work and thank you to share the code.
The medel of SE-ResNet-50 offered in the link can not be downloaded.
I would like to reimplement your work. Could you please help me. 
Thank you very much. Best wishes.

**Comment by fvmassoli** [comment]
You should ask to the owner of the VGGFace2 github repo
