### ISSUE TITLE
renet50_ft

### ISSUE THREAD

**Issue by XIAOKANGWANDE666** [fvmassoli/cross-resolution-face-recognition#2]
hi. i download renet50_ft,but code runs wrong.
AttributeError: 'collections.OrderedDict' object has no attribute 'parameters'
could you please share the renet50-ft you use?

**Comment by fvmassoli** [comment]
The model you need is the senet50_ft not the resnet50_ft. 
You can find the model in original web page of the VGGFace2 paper (https://github.com/ox-vgg/vgg_face2); it is the 

SE-ResNet-50 | 2048 | Y

model

**Comment by XIAOKANGWANDE666** [comment]
I check it.The model I download is no problem.It is the SE-ResNet-50 | 2048 | Y from that address.I run the code with pytorch-gpu python3.6.It appears:AttributeError: 'collections.OrderedDict' object has no attribute 'parameters',too.It appears at utils.py:tm=torch.load(model_base_path).I only modify model_base_path's default and dset-base-path's default. I don't know what I do wrong?I search the problem in internet but it doesn't work.

**Comment by fvmassoli** [comment]
I run the code with python 3.6.9 and pytorch 1.4.0 and it works perfectly. 
I tried to download the senet50_ft checkpoint from the vggface2 repo and it gives me the same error. I think the problem is that they changed the way they save the checkpoint from the time I downloaded the model. 
I added the link to my base model checkpoint in the README and below here

https://drive.google.com/file/d/17AVPBQFtrIJwo3yPm4sNls7ZSyswFsvT/view?usp=sharing

**Comment by XIAOKANGWANDE666** [comment]
I download your model,but it fails,too.It appears:UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1124: ordinal not in range(128) at main.py:sm, tm = load_models(args.model_base_path, device, args.model_ckp).I searched the internet，it said that the python version that model saved is different from the one my code use. But I run it at ubuntu18.04 pytorch-gpu=1.0 python=3.6,Ithink it shuold no problem.The code enviroment you use is something different?

**Comment by fvmassoli** [comment]
The problem might be due to an issue with files pickled from Python 2 and loaded in Python 3. Have a look here:

https://stackoverflow.com/questions/11305790/pickle-incompatibility-of-numpy-arrays-between-python-2-and-3

On my laptop I have python 3.6.9, torch 1.4.0 and pickle 4.0

**Comment by XIAOKANGWANDE666** [comment]
I don't get some help with it.But I try to change the version of pytorch(from1.0 to 1.4).I found it can load your model.But it appears:AttributeError:'KitModel' object has no attribute 'get_model_state_dict' at 74 lines at trainer.py.I seacch it(self._student.get_model_state_dict()) and I delect .get_model_state_dict().It leaves:self._student. I found that error disappears.Idon't konw why?could I can delete it?

**Comment by fvmassoli** [comment]
This was a bug. Thanks for noticing it. The proper method to call is .state_dict().
I corrected the issue and pushed the code

**Comment by fvmassoli** [comment]
> Thanks!Could you please provide the test code about your paper?I very want to test the model.thank you very much.

This is something I planned to do but. I will need some time to clean the code and upload it.

In the mean while you can have a look at the code here:

https://github.com/ox-vgg/vgg_face2/tree/master/standard_evaluation

Concerning the IJB-B and IJB-C datasets, my test code is very similar the one available in the link above. I just modified it so to take care of the various features resolutions. 

Concerning all the other datasets, I simply followed the protocols shipped with the datasets themselves.
