### ISSUE TITLE
Losses and accuracy wierd

### ISSUE THREAD

**Issue by supersyz** [fvmassoli/cross-resolution-face-recognition#6]
Hi，thx for your previous help ,
I tried  SGD again,the accuracy seems to stuck at 20%, And All losses begin to grow with accuracy decreasing.
I don't know if it's because lack of training or something wrong. Could you tell me how many epoch did you train the model well?

And by the way,did you succeeded by using default hyper parameters?  If so,maybe I made the data set wrong,because I can not.
But it seems to be much better when I adjust learning rate to 0.0001.

**Comment by fvmassoli** [comment]
Please, move this quesion to the "Discussions" section of the repo
